# -*- coding: utf-8 -*-
"""Student.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xWqP1wmIzvxXlL_N92FWQrzAiCHozK_j
"""

# importing excel files into google colab
from google.colab import files
upload = files.upload()

# declaring library and reading excel to create new dataframes
import pandas as pd
dfc = pd.read_excel (r'/content/Concordia.xlsx')
dfm = pd.read_excel (r'/content/McGill.xlsx')
dft = pd.read_excel (r'/content/TREBAS.xlsx')

# Creating new column & locking it too single value
dfc.loc[:,'College'] = 'Concordia'
dfm.loc[:,'College'] = 'Mcgill'
dft.loc[:,'College'] = 'Trebas'

# Renaming the column name within the dataframes
dfm.rename(columns = {'Student_Code':'ID'}, inplace = True)
dfc.rename(columns = {'Student_Code':'ID', 'Full_Name':'Name', 'Nationality':'Country'}, inplace = True)
dft['Name']=dft.apply(lambda x:'%s %s' % (x['First_Name'],x['Last_Name']),axis=1)


# Creating new dataframe by joining all dataframes with unique single column
df = pd.concat([dfc, dfm, dft], axis=0)
print (df)

# Exporting the dataframe to excel
df.to_excel("Student.xlsx",sheet_name='Details')

